# Generated by Django 4.1.1 on 2022-10-05 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='OperatorConfirmUUID',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Operator Confirm Code',
                'verbose_name_plural': 'Operator Confirm Codes',
                'db_table': 'operator_confirm_code',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('ua', 'Ukrainian'), ('en', 'English')], default='ua', max_length=2)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'db_table': 'telegram_user',
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.telegramuser')),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'db_table': 'support_request',
            },
        ),
    ]
